### ISSUE TITLE
Missing develop branch

### ISSUE THREAD

**Issue by gilliek** [Checkmarx/Go-SCP#1]
Hi,

I'd like to submit a pull request but, according to your "How to contribute" guide, I should submit it to the `develop` branch:

> Once you're ready to merge your work with others, you should go to main repository and open a Pull Request to the develop branch.

However, there is no such a branch in your repository. Could you create it or can I submit the pull request to the `master` branch?

Thanks,

Kevin

**Comment by ErezYalon** [comment]
Hi Kevin,

For now, submit to the `master` branch.

Thanks,
Erez

**Comment by gilliek** [comment]
Ok, thanks.

Kevin

**Comment by PauloASilva** [comment]
Hi @gilliek,
We did update the repo with all stuff and structure required for easier maintainability and development.
Right now everything should work as documented on "How To Contribute" section and from now on Pull Requests should be opened to the `develop` branch.

Please let me know if you need help to sync your fork.

Regards,
Paulo

**Comment by gilliek** [comment]
Hi @PauloASilva,

Thank you. Do you want me to merge my actual pull requests with the `develop` branch instead of `master`?

Best,
Kevin

**Comment by PauloASilva** [comment]
Hi @gilliek,
This would be awesome from you

Can you first sync your fork with this repo and then merge updated `develop` into your feature branch?
I think this way we will avoid conflicts.

Best,
Paulo

**Comment by gilliek** [comment]
Sure, I can do that.

Best,
Kevin

**Comment by gilliek** [comment]
I merged my feature branches et updated the pull request. It should be ok now.

Best,
Kevin

**Comment by PauloASilva** [comment]
Hi @gilliek 
Just to let you know that on [v1.0.2][1] we had to rename the `docs` folder to `src` due to [github-linguist][2] misbehaviour: `docs` was being ignored, leading to wrong repository categorization.

I had to do it before reviewing your Pull Requests, so they are broken again: sorry about that.
If you're available to merge and update them, fantastic, otherwise I will do it myself locally but I am afraid it will take longer.

Thanks again for your contributions.

Regards,
Paulo


[1]: https://github.com/Checkmarx/Go-SCP/releases/tag/v1.0.2
[2]: https://github.com/github/linguist

**Comment by gilliek** [comment]
Hi @PauloASilva,

I merged and updated my PR.

Best,
Kevin
