### ISSUE TITLE
Clarify how internal redirects work

### ISSUE THREAD

**Issue by jabley** [Checkmarx/Go-SCP#27]
From https://github.com/Checkmarx/Go-SCP/blob/c3471ef24a7c2ca6a769457783f43c60712f087a/input-validation/validation.md:

> Go handles redirections internally which means that unless specified in the server side, in case of a redirect, Go serves the target page of the redirect directly. This can lead to security issues if a bad agent submits malicious data directly to the target of the redirection, effectively bypassing the data validation procedures in the server.

Please clarify how this works, with code examples using the standard library.

I'm not sure what it's trying to say. If I use https://golang.org/pkg/net/http/#Redirect, it doesn't appear to handle the redirection internally. It will send a 3xx response to the client, and wait for another request to arrive.

**Comment by jparnaut** [comment]
I agree, the way it's written is confusing. I'll run some tests, rewrite and try to include a clearer explanation in the next milestone. 

Thank you @jabley.

**Comment by jparnaut** [comment]
Well, after running some tests with `http.Redirect` it does send a 301 response and the access controls are enforced against the target of the redirect. 
It seems to me that Go redirects don't bypass the validation procedures, at least not as described in this case.  

I'll remove this from the next version since it's incorrect.

Thanks again for checking @jabley.
