### ISSUE TITLE
suggestion: be more precise in hashing language

### ISSUE THREAD

**Issue by kardianos** [Checkmarx/Go-SCP#5]
On page
https://github.com/Checkmarx/Go-SCP/blob/b6faece923bfdccfcc04de1b3994752721ef1ce3/docs/cryptographic-practices/README.md

both MD5 and SHA256 are discussed. SHA256 is stated to be "stronger".

It may be more precise to say that "MD5 and SHA1 may be susceptible to hash collision attacks (making the same hash from different content), while SHA256 is not known to be susceptible to such collisions."

**Comment by jeffallen** [comment]
The only discussion of MD5 should be, "MD5 was used in the past but is no longer safe. Do not design new systems that use it. Work actively to replace it in existing systems." See https://security.stackexchange.com/questions/52461/how-weak-is-md5-as-a-password-hashing-function for example.

**Comment by kardianos** [comment]
Well, I hope you are using neither MD5 or SHA256 for hashing a password. If this is what is intended, then the page needs a rewrite.

**Comment by PauloASilva** [comment]
Hi @kardianos,
I see your point and I agree to make "stronger", more precise.

@jeffallen Being "too fast" makes MD5 not a proper choice for password hashing, but there are still use cases where MD5 is a viable choice exactly because it is fast.

MD5 is the most well known hashing algorithm so I think it worth to be here so that readers feel themselves comfortable with the subject. Nevertheless your concern is valid when talking about password hashing.

I will work on detailing hash collisions and Rainbow Tables attacks.

**Comment by Jack64** [comment]
@kardianos @jeffallen I'd appreciate your comments to my change suggestions on https://github.com/Checkmarx/Go-SCP/pull/31
